FROM python:3.7-alpine

WORKDIR /app

# Install build tools using APK (Alpine Linux)
RUN apk add --no-cache \
        gcc \
        musl-dev \
        build-base

COPY requirements.txt .

RUN pip uninstall -y thriftpy thriftpy2 || true

RUN pip install --upgrade pip setuptools wheel --default-timeout=300 --retries 20 && \
    pip install --default-timeout=300 --retries 20 --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 8003

CMD ["python", "main.py"]
